#ifndef EXTERNAL_FLASH_LAYOUT_H
#define EXTERNAL_FLASH_LAYOUT_H

#include "error_code.h"

#include <stdint.h>

#define EXTERNAL_FLASH_TOTAL_SIZE 0x01000000u
#define EXTERNAL_FLASH_PAGE_SIZE 0x00000100u
#define EXTERNAL_FLASH_SECTOR_SIZE 0x00001000u
#define EXTERNAL_FLASH_JEDEC_ID 0x00EF4018u

#define EXTERNAL_FLASH_OTA_STAGING_START 0x00000000u
#define EXTERNAL_FLASH_OTA_STAGING_SIZE 0x00200000u
#define EXTERNAL_FLASH_OTA_METADATA_START 0x00200000u
#define EXTERNAL_FLASH_OTA_METADATA_SIZE 0x00001000u
#define EXTERNAL_FLASH_CONFIG_A_START 0x00201000u
#define EXTERNAL_FLASH_CONFIG_A_SIZE 0x00001000u
#define EXTERNAL_FLASH_CONFIG_B_START 0x00202000u
#define EXTERNAL_FLASH_CONFIG_B_SIZE 0x00001000u
#define EXTERNAL_FLASH_CRASH_START 0x00203000u
#define EXTERNAL_FLASH_CRASH_SIZE 0x0000D000u
#define EXTERNAL_FLASH_ALARM_LOG_START 0x00210000u
#define EXTERNAL_FLASH_ALARM_LOG_SIZE 0x00100000u
#define EXTERNAL_FLASH_RUNTIME_LOG_START 0x00310000u
#define EXTERNAL_FLASH_RUNTIME_LOG_SIZE 0x00400000u
#define EXTERNAL_FLASH_RESERVED_START 0x00710000u
#define EXTERNAL_FLASH_RESERVED_SIZE 0x008F0000u

#if (EXTERNAL_FLASH_OTA_STAGING_START + EXTERNAL_FLASH_OTA_STAGING_SIZE) != \
    EXTERNAL_FLASH_OTA_METADATA_START
#error "OTA staging and metadata layout is not contiguous"
#endif
#if (EXTERNAL_FLASH_RESERVED_START + EXTERNAL_FLASH_RESERVED_SIZE) != \
    EXTERNAL_FLASH_TOTAL_SIZE
#error "External Flash layout does not cover W25Q128 capacity"
#endif

typedef enum {
    EXTERNAL_FLASH_PARTITION_OTA_STAGING = 0,
    EXTERNAL_FLASH_PARTITION_OTA_METADATA,
    EXTERNAL_FLASH_PARTITION_CONFIG_A,
    EXTERNAL_FLASH_PARTITION_CONFIG_B,
    EXTERNAL_FLASH_PARTITION_CRASH,
    EXTERNAL_FLASH_PARTITION_ALARM_LOG,
    EXTERNAL_FLASH_PARTITION_RUNTIME_LOG,
    EXTERNAL_FLASH_PARTITION_RESERVED,
    EXTERNAL_FLASH_PARTITION_COUNT
} external_flash_partition_id_t;

typedef struct {
    uint32_t start;
    uint32_t size;
} external_flash_partition_t;

const external_flash_partition_t *external_flash_partition_get(
    external_flash_partition_id_t id);
status_t external_flash_layout_validate(void);

#endif
