#ifndef OTA_STAGING_FORMAT_H
#define OTA_STAGING_FORMAT_H

/** Shared W25Q128 staging metadata wire contract. */
#define OTA_STAGING_METADATA_MAGIC 0x4F54414Du
#define OTA_STAGING_METADATA_VERSION 1u
#define OTA_STAGING_METADATA_WIRE_SIZE 236u
#define OTA_STAGING_METADATA_CRC_OFFSET 232u

#endif
